# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(871, 452)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("chime_in.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(330, 10, 241, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditCadena = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadena.setGeometry(QtCore.QRect(20, 340, 831, 31))
        self.lineEditCadena.setAutoFillBackground(False)
        self.lineEditCadena.setFrame(True)
        self.lineEditCadena.setClearButtonEnabled(True)
        self.lineEditCadena.setObjectName("lineEditCadena")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 320, 131, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.textEditCFG = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCFG.setGeometry(QtCore.QRect(330, 30, 521, 201))
        self.textEditCFG.setStyleSheet("")
        self.textEditCFG.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textEditCFG.setFrameShadow(QtWidgets.QFrame.Plain)
        self.textEditCFG.setObjectName("textEditCFG")
        self.btnGuardarCFG = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuardarCFG.setGeometry(QtCore.QRect(670, 240, 81, 31))
        self.btnGuardarCFG.setFlat(False)
        self.btnGuardarCFG.setObjectName("btnGuardarCFG")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 290, 831, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.lineEditCFGVF = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCFGVF.setEnabled(False)
        self.lineEditCFGVF.setGeometry(QtCore.QRect(330, 240, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lineEditCFGVF.setFont(font)
        self.lineEditCFGVF.setMouseTracking(False)
        self.lineEditCFGVF.setAutoFillBackground(False)
        self.lineEditCFGVF.setStyleSheet("color: rgb(255, 0, 0);")
        self.lineEditCFGVF.setText("")
        self.lineEditCFGVF.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCFGVF.setReadOnly(True)
        self.lineEditCFGVF.setPlaceholderText("")
        self.lineEditCFGVF.setObjectName("lineEditCFGVF")
        self.lineEditCadenaVF = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadenaVF.setEnabled(False)
        self.lineEditCadenaVF.setGeometry(QtCore.QRect(20, 380, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditCadenaVF.setFont(font)
        self.lineEditCadenaVF.setMouseTracking(False)
        self.lineEditCadenaVF.setStyleSheet("color: rgb(0, 170, 0);")
        self.lineEditCadenaVF.setText("")
        self.lineEditCadenaVF.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEditCadenaVF.setReadOnly(True)
        self.lineEditCadenaVF.setPlaceholderText("")
        self.lineEditCadenaVF.setObjectName("lineEditCadenaVF")
        self.btnEliminarCFG = QtWidgets.QPushButton(self.centralwidget)
        self.btnEliminarCFG.setGeometry(QtCore.QRect(570, 240, 81, 31))
        self.btnEliminarCFG.setObjectName("btnEliminarCFG")
        self.btnGraficar = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraficar.setGeometry(QtCore.QRect(770, 380, 81, 31))
        self.btnGraficar.setWhatsThis("")
        self.btnGraficar.setObjectName("btnGraficar")
        self.btnArchivos = QtWidgets.QPushButton(self.centralwidget)
        self.btnArchivos.setGeometry(QtCore.QRect(670, 380, 81, 31))
        self.btnArchivos.setWhatsThis("")
        self.btnArchivos.setObjectName("btnArchivos")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 30, 291, 241))
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.btnNuevoCFG = QtWidgets.QPushButton(self.centralwidget)
        self.btnNuevoCFG.setGeometry(QtCore.QRect(770, 240, 81, 31))
        self.btnNuevoCFG.setFlat(False)
        self.btnNuevoCFG.setObjectName("btnNuevoCFG")
        self.lineEditCadenaVF.raise_()
        self.lineEditCFGVF.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.btnGuardarCFG.raise_()
        self.line_2.raise_()
        self.btnEliminarCFG.raise_()
        self.btnGraficar.raise_()
        self.btnArchivos.raise_()
        self.textEditCFG.raise_()
        self.lineEditCadena.raise_()
        self.tableWidget.raise_()
        self.btnNuevoCFG.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 871, 21))
        self.menubar.setObjectName("menubar")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionComo_usar = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/alexi/Dropbox/Mi Carpeta/Iconos/question1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionComo_usar.setIcon(icon1)
        self.actionComo_usar.setObjectName("actionComo_usar")
        self.actionAcerca_de = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("C:/Users/alexi/Dropbox/Mi Carpeta/Iconos/info1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAcerca_de.setIcon(icon2)
        self.actionAcerca_de.setObjectName("actionAcerca_de")
        self.menuAyuda.addAction(self.actionComo_usar)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionAcerca_de)
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CFG"))
        self.label.setText(_translate("MainWindow", "Gramáticas guardadas"))
        self.label_2.setText(_translate("MainWindow", "Escribir CFG"))
        self.lineEditCadena.setPlaceholderText(_translate("MainWindow", "aab"))
        self.label_3.setText(_translate("MainWindow", "Escribir cadena a validar"))
        self.textEditCFG.setPlaceholderText(_translate("MainWindow", "S -> \'a\' S | \'b\'"))
        self.btnGuardarCFG.setToolTip(_translate("MainWindow", "Guardar o editar CFG"))
        self.btnGuardarCFG.setText(_translate("MainWindow", "Guardar"))
        self.btnEliminarCFG.setToolTip(_translate("MainWindow", "Eliminar CFG"))
        self.btnEliminarCFG.setText(_translate("MainWindow", "Eliminar"))
        self.btnGraficar.setToolTip(_translate("MainWindow", "Graficar arboles"))
        self.btnGraficar.setText(_translate("MainWindow", "Graficar"))
        self.btnArchivos.setToolTip(_translate("MainWindow", "Ver arboles generados"))
        self.btnArchivos.setText(_translate("MainWindow", "Mis archivos"))
        self.btnNuevoCFG.setToolTip(_translate("MainWindow", "Escribir nuevo CFG"))
        self.btnNuevoCFG.setText(_translate("MainWindow", "Nuevo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.actionComo_usar.setText(_translate("MainWindow", "Cómo usar"))
        self.actionAcerca_de.setText(_translate("MainWindow", "Acerca de"))

