# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(720, 449)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listViewCFG = QtWidgets.QListView(self.centralwidget)
        self.listViewCFG.setGeometry(QtCore.QRect(20, 30, 191, 351))
        self.listViewCFG.setStyleSheet("")
        self.listViewCFG.setObjectName("listViewCFG")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(220, 10, 20, 371))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 191, 16))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(250, 10, 241, 16))
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.lineEditCadena = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditCadena.setGeometry(QtCore.QRect(250, 320, 451, 21))
        self.lineEditCadena.setObjectName("lineEditCadena")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 300, 241, 16))
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.btnGraficarArbol = QtWidgets.QPushButton(self.centralwidget)
        self.btnGraficarArbol.setGeometry(QtCore.QRect(600, 350, 101, 31))
        self.btnGraficarArbol.setObjectName("btnGraficarArbol")
        self.textEditCFG = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditCFG.setGeometry(QtCore.QRect(250, 30, 451, 201))
        self.textEditCFG.setObjectName("textEditCFG")
        self.btnGuardarCFG = QtWidgets.QPushButton(self.centralwidget)
        self.btnGuardarCFG.setGeometry(QtCore.QRect(600, 240, 101, 31))
        self.btnGuardarCFG.setObjectName("btnGuardarCFG")
        self.labelInfoCFG = QtWidgets.QLabel(self.centralwidget)
        self.labelInfoCFG.setGeometry(QtCore.QRect(250, 245, 341, 31))
        self.labelInfoCFG.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelInfoCFG.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelInfoCFG.setText("")
        self.labelInfoCFG.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelInfoCFG.setObjectName("labelInfoCFG")
        self.labelCadenaVF = QtWidgets.QLabel(self.centralwidget)
        self.labelCadenaVF.setGeometry(QtCore.QRect(250, 350, 341, 31))
        self.labelCadenaVF.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelCadenaVF.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.labelCadenaVF.setText("")
        self.labelCadenaVF.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.labelCadenaVF.setObjectName("labelCadenaVF")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(250, 280, 451, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 720, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CFG"))
        self.label.setText(_translate("MainWindow", "Gramáticas guardadas"))
        self.label_2.setText(_translate("MainWindow", "Escribir CFG"))
        self.lineEditCadena.setPlaceholderText(_translate("MainWindow", "aab"))
        self.label_3.setText(_translate("MainWindow", "Escribir cadena a validar"))
        self.btnGraficarArbol.setText(_translate("MainWindow", "Graficar Arboles"))
        self.textEditCFG.setPlaceholderText(_translate("MainWindow", "S -> \'a\' S | \'b\'"))
        self.btnGuardarCFG.setText(_translate("MainWindow", "Guardar CFG"))

